CREATE SEQUENCE TBL_USUARIOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USUARIOS (
    ID INTEGER DEFAULT TBL_USUARIOS_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    SOBRENOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL
);