CREATE SEQUENCE TBL_PREFERENCIAS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_PREFERENCIAS_USUARIO (
    ID INTEGER DEFAULT TBL_PREFERENCIAS_SEQ.NEXTVAL NOT NULL,
    cor_tema VARCHAR(255),
    notificacoes_email NUMBER(1),
    usuario_id INTEGER NOT NULL,
    CONSTRAINT pk_preferencias_usuario PRIMARY KEY (ID),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES tbl_usuarios(id)
);
